<?php

/**
 *
 * @package    Gems
 * @subpackage Snippets\Ask
 * @author     Matijs de Jong <mjong@magnafacta.nl>
 * @copyright  Copyright (c) 2012 Erasmus MC
 * @license    New BSD License
 */

namespace Gems\Snippets\Ask;

use Gems\Communication\CommunicationRepository;
use Gems\MenuNew\RouteHelper;
use Gems\Tracker;
use Gems\Tracker\Snippets\ShowTokenLoopAbstract;
use Gems\Tracker\Token;
use MUtil\Translate\Translator;
use Zalt\Base\RequestInfo;
use Zalt\Html\HtmlInterface;
use Zalt\Message\MessengerInterface;
use Zalt\SnippetsLoader\SnippetOptions;

/**
 * Loops through all open surveys and then shows an endmessage
 *
 * Works using $project->getAskDelay()
 *
 * @package    Gems
 * @subpackage Snippets\Ask
 * @copyright  Copyright (c) 2012 Erasmus MC
 * @license    New BSD License
 * @since      Class available since version 1.6.1
 */
class RedirectUntilGoodbyeSnippet extends ShowTokenLoopAbstract
{
    protected string $clientIp;

    /**
     * Optional, calculated from $token
     */
    protected Token $currentToken;

    public function __construct(
        SnippetOptions $snippetOptions,
        RequestInfo $requestInfo,
        RouteHelper $routeHelper,
        CommunicationRepository $communicationRepository,
        Translator $translator,
        protected Tracker $tracker,
        protected MessengerInterface $messenger,
    ) {
        parent::__construct($snippetOptions, $requestInfo, $routeHelper, $communicationRepository, $translator);
    }

    /**
     * Create the snippets content
     *
     * This is a stub function either override getHtmlOutput() or override render()
     *
     * @return HtmlInterface Something that can be rendered
     */
    public function getHtmlOutput()
    {
        $messages = false;

        if ($this->wasAnswered) {
            $this->currentToken = $this->token->getNextUnansweredToken();
        } else {
            $validator = $this->tracker->getTokenValidator($this->clientIp);

            if ($validator->isValid($this->token->getTokenId())) {
                $this->currentToken = $this->token;
            } else {
                $messages = $validator->getMessages();
                $this->currentToken = $this->token->getNextUnansweredToken();
            }
        }

        if ($this->checkContinueLinkClicked()) {
            // Continue later was clicked, handle the click
            return $this->continueClicked();

        } elseif ($this->currentToken instanceof Token) {
            $url = $this->getTokenUrl($this->currentToken);

            // Redirect at once
            header('Location: ' . $url);
            exit();
        }

        // After the header() so that the patient does not see the messages after answering surveys
        if ($messages) {
            $this->messenger->addMessages($messages);
        }

        $org  = $this->token->getOrganization();
        $html = $this->getHtmlSequence();

        $html->h3($this->getHeaderLabel());
        $html->append($this->formatThanks());
        if ($welcome = $org->getWelcome()) {
            $html->pInfo()->raw($welcome);
        }

        $p = $html->pInfo()->spaced();
        if ($this->wasAnswered) {
            $p->append($this->translator->_('Thanks for answering our questions.'));
        } elseif (! $this->token->isCurrentlyValid()) {
            if ($this->token->isExpired()) {
                $this->messenger->addMessage($this->translator->_('This survey has expired. You can no longer answer it.'));
            } else {
                $this->messenger->addMessage($this->translator->_('This survey is no longer valid.'));
            }
        }
        $p->append($this->translator->_('We have no further questions for you at the moment.'));
        $p->append($this->translator->_('We appreciate your cooperation very much.'));

        if ($sig = $org->getSignature()) {
            $html->pInfo()->raw($sig);
        }

        return $html;
    }

    public function hasHtmlOutput(): bool
    {
        return parent::hasHtmlOutput(); // TODO: Change the autogenerated stub
    }
}
