<?php
/**
 * @package    Gems
 * @subpackage Snippets
 * @copyright  Copyright (c) 2011 Erasmus MC
 * @license    New BSD License
 * @version    $Id$
 */

/**
 * Header for html/pdf export of a respondent
 *
 * @package    Gems
 * @subpackage Snippets
 * @copyright  Copyright (c) 2011 Erasmus MC
 * @license    New BSD License
 * @since      Class available since version 1.5.5
 */
class Gems_Snippets_Export_ReportHeaderSnippet extends \MUtil_Snippets_SnippetAbstract
{
    /**
     *
     * @var \Gems_User_Organization
     */
    protected $currentOrganization;

    /**
     *
     * @var \Gems_User_User
     */
    protected $currentUser;

    public function getHtmlOutput(\Zend_View_Abstract $view)
    {
        $html = $this->getHtmlSequence();
        $html->h2($this->_('Respondent report'));

        $table = $html->table(array('class' => 'browser'));

        $table->th($this->_('Report information'), array('colspan' => 2));
        $tr = $table->tr();
        $tr->th($this->_('Generated by'));
        $tr->td($this->currentUser->getFullName());
        $tr = $table->tr();
        $tr->th($this->_('Generated on'));
        $tr->td(new \Zend_Date());
        $tr = $table->tr();
        $tr->th($this->_('Organization'));
        $tr->td($this->currentOrganization->getName());

        $html->br();

        return $html;
    }
}