engines:       
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: tests/phpmdruleset.xml
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- tests/**/*
- classes/Gems/User/Adapter/Radius/radius.class.php
