
CREATE TABLE n1 (
    id INTEGER NOT NULL PRIMARY KEY,
    c1 VARCHAR(10),
    c2 VARCHAR(10)
);

CREATE TABLE n2 (
    cid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    pid INTEGER NOT NULL,
    c1 VARCHAR(10),
    c2 VARCHAR(10)
);
