<?php 
    header("Content-Type: application/download");
    header("Content-Disposition: attachment; filename=\"" . $this->filename . "\"");
    header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");    // Date in the past
    header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
    header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
    header("Pragma: cache");                          // HTTP/1.0
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=Content-Type content="text/html; charset=UTF-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<style>
    /* Default styles for tables */

    table {
        border-collapse: collapse;
        border: .5pt solid #000000;
    }

    tr th {
        font-weight: bold;
        padding: 3px 8px;
        border: .5pt solid #000000;
        background: #c0c0c0	
    }
    tr td {
        padding: 3px 8px;
        border: .5pt solid #000000;
    }
    td {mso-number-format:"\@";}
</style>
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>