<?php echo $this->doctype(); ?>
<html <?php echo 'xmlns="http://www.w3.org/1999/xhtml" xml:lang="'.$this->locale.'"' ?> lang="<?php echo $this->locale; ?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headMeta(); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    echo $this->headTitle();
    if ($this->jQuery) {
        echo $this->jQuery()->renderStylesheets();
    }
    if (\MUtil_Bootstrap::enabled()) {
        echo MUtil_Bootstrap::bootstrap()->renderStylesheets();
    }
    echo $this->headLink();
    echo $this->headStyle();
    ?>

</head>
<body>
    <div id="container" class="container-fluid">
        <div class="content">
            <div id="main-container">
                <div id="main" class="container-fluid">
                    <?php
                    if ($this->main) {
                        echo $this->main->render($this);
                    }
                    echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </div>


<?php if ($this->jQuery) {
        //echo
        echo $this->jQuery()->renderJavascript();
    }
    if (\MUtil_Bootstrap::enabled()) {
        echo \MUtil_Bootstrap::bootstrap()->renderJavascript();
    }
?>
<script type="text/javascript" <?php echo isset($this->nonceString) ? $this->nonceString : ''; ?>>
$(function() {

    $('#menu-toggle').on('click', function() {
        var menuCollapse = $('#menu-collapse');
        menuCollapse.toggleClass('active').removeClass('hidden');
        $('#menu-collapse-backdrop').toggleClass('active').removeClass('hidden');

        var menuHeight = window.document.documentElement.clientHeight - $('.main-menu').height();
        menuCollapse.css('height', menuHeight+'px');
    });

    $('#menu-collapse-backdrop').on('click', function(e) {
        $('#menu-collapse').removeClass('active');
        $('#menu-collapse-backdrop').removeClass('active');
    });

});

</script>
<?php
echo \MUtil_Echo::out();
echo $this->headScript();
echo $this->inlineScript();
?>
</body>
</html>