<?php echo $this->doctype(); ?>
<html <?php echo 'xmlns="http://www.w3.org/1999/xhtml" xml:lang="'.$this->locale.'"' ?> lang="<?php echo $this->locale; ?>">
<head>
    <?php
    echo $this->headMeta();
    echo $this->headTitle();
    echo $this->headLink();
    echo $this->headStyle();

    // Check if jQuery library is needed
    if ($this->jQuery) {
        echo $this->jQuery();
    }
    ?>
    </head>
<body>
    <div <?php echo 'id="' . ($this->navigation ? 'all' : 'all_full_width') . '"'; ?> >
        <div id="header"><?php if ($this->header) { echo $this->header->render($this); }?></div>
        <div id="header_bar"><?php if ($this->header_bar) { echo $this->header_bar->render($this); } ?></div>
<?php
    if ($this->navigation || $this->menuHtml):
?>
    <div id="main"><?php
        if ($this->main) {
            echo $this->main->render($this);
        }
        echo $this->layout()->content;
    ?></div>
    <div id="menu"><?php
        echo $this->navigation()->menu();
        echo $this->menuHtml;
    ?></div><?php
    else:
    ?><div id="main_full_width"><?php
        if ($this->main) {
            echo $this->main->render($this);
        }
        echo $this->layout()->content;
    ?></div><?php
    endif;
    ?>
    <div id="footer"><?php
    if ($this->footer) {
        echo $this->footer->render($this);
    }
    ?></div>
    </div><?php
    echo \MUtil_Echo::out();

    // Scripts here for load optimization
    echo $this->headScript();
    echo $this->inlineScript();
?></body>
</html>