<?php
// ENGLISH
if ('en' == $this->locale->getLanguage()):
?>
<h3>Reporting bugs</h3>

<p class="info">
    <?php echo $this->project->name; ?> uses the <a href="http://www.mantisbt.org/" rel="external">Mantis Bug Tracker</a>
    for reporting and solving bugs.
    <br/>
    To help us to quickly solve bugs we request you read the suggestions below.
</p>

<div class="indent">
    <h4>Report each bug by itself</h4>
    <p class="info">
        Every bug has to be assigned to someone to solve it.
        Combining multiple problems in a single report can obstruct this process.
    </p>
    <h4>Add a link</h4>
    <p class="info">
        If a problem is on a specific page, copy the address of the page from the addressbar of your browser.
    </p>
    <h4>Add a screenshot</h4>
    <p class="info">
        Usually a screenshot helps us to solve the problem quicker.
    </p>
    <ul class="indent">
        <li>Press <p style="font-family: monospace;">[Alt]^[Print Screen]</p>.</li>
        <li>Open Paint or another drawing package or even Word.</li>
        <li>Paste the clipboard and save the result as a file.</li>
        <li>Add this file to the bug using "Upload File" in the bug tracker.</li>
    </ul>
    <h4>Make an account</h4>
    <p class="info">
        This takes little effort and enables us to request extra information when we need it to solve the bug
        and allows us to report to you when the problem is solved.
    </p>
</div>

<div class="centerAlign">
    <a href="<?php echo $this->project->contact['bugsUrl'] ?>" class="actionlink" rel="external" target="pulse_bugs">Report a bug</a>
</div><?php
endif;

// NEDERLANDS
if ('nl' == $this->locale->getLanguage()):
?>
<h3>Problemen melden</h3>

<p class="info">
    <?php echo $this->project->name; ?> gebruikt de <a href="http://www.mantisbt.org/" rel="external">Mantis Bug Tracker</a>
    voor de rapportage en verwerking van problemen.
    <br/>
    Voor een snelle verwerking van problemen verzoeken wij u de onderstaande suggesties te lezen.
</p>

<div class="indent">
    <h4>Meld elk probleem apart</h4>
    <p class="info">
        Elk probleem moet aan iemand toegewezen worden voor behandeling.
        Dit kan lastig zijn als verschillende problemen in &eacute;&eacute;n melding staan.
    </p>
    <h4>Voeg een link toe</h4>
    <p class="info">
        Als het probleem speelt op een specifieke pagina, kopieer dan het adres van de pagina uit de adresbalk van de browser.
    </p>
    <h4>Voeg een screenshot toe</h4>
    <p class="info">
        Met een screenshot kunnen wij een probleem meestal sneller oplossen.
    </p>
    <ul class="indent">
        <li>Druk op <p style="font-family: monospace;">[Alt]^[Print Screen]</p>.</li>
        <li>Open Paint of een ander tekenpakket of desnoods Word.</li>
        <li>Plak (paste) de inhoud van het clipboard en sla het bestand op.</li>
        <li>Voeg het bestand toe aan de melding middels "Upload File" in de bug tracker.</li>
    </ul>
    <h4>Maak een account aan</h4>
    <p class="info">
        Dit kost weinig tijd en hierdoor kunnen wij u extra informatie vragen als dat nodig is om het probleem op te lossen
        en kunnen wij u op de hoogte te stellen van de voortgang.
    </p>
</div>

<div class="centerAlign">
    <a href="<?php echo $this->project->contact['bugsUrl'] ?>" class="actionlink" rel="external" target="pulse_bugs">Meld een probleem</a>
</div><?php
endif; ?>
