<?php

$bugsUrl = $this->project->getBugsUrl();
if (preg_match('/github/', $bugsUrl)) {
    $issueTracker = 'GitHub';
    $issueType    = 'Issue Tracker';
} elseif (preg_match('/mantis/', $bugsUrl)) {
    $issueTracker = 'Mantis';
    $issueType    = 'Bug Tracker';
} else {
    $issueTracker = '';
    $issueType    = 'Tracker';
}


// ENGLISH
if ('en' == $this->locale->getLanguage()):
?>
<h3>About bug reporting</h3>

<p class="info">
    <?php echo $this->project->name; ?> uses the
    <a href="<?php echo $this->project->getBugsUrl(); ?>" rel="external" target="pulse_bugs"><?php echo $issueTracker . ' ' . $issueType; ?></a>
    for reporting and solving issues.
    <br/>
    To help us to quickly solve bugs we request you read the suggestions below.
</p>

<div class="indent">
    <h4>Make an account<?php echo ($issueTracker ? (' on ' . $issueTracker) : ''); ?></h4>
    <p class="info">
        You need a (free) account<?php echo ($issueTracker ? (' on ' . $issueTracker) : ''); ?> to report issues.
    </p>
    <h4>Report each bug by itself</h4>
    <p class="info">
        Every bug has to be assigned to someone to solve it.
        Combining multiple problems in a single issue can obstruct this process.
    </p>
    <h4>Add a link</h4>
    <p class="info">
        If a problem is on a specific page, copy the address of the page from the addressbar of your browser.
    </p>
    <h4>Add a screenshot</h4>
    <p class="info">
        Usually a screenshot helps us to solve the problem quicker.
    </p>
    <ul>
        <li>Press <span style="font-family: monospace;">[Alt]^[Print Screen]</span>.</li>
        <li>Open Paint or another drawing package or even Word.</li>
        <li>Paste the clipboard and save the result as a file.</li>
        <li>Add this file to the issue.</li>
    </ul>
</div>


<h3>Report a bug</h3>

<p class="info">
    You can find the
    <a href="<?php echo $this->project->getBugsUrl(); ?>" rel="external" target="pulse_bugs"><?php echo $issueTracker . ' ' . $issueType; ?> here</a>.
</p><?php endif;

// NEDERLANDS
if ('nl' == $this->locale->getLanguage()):
?>
<h3>Over het melden van problemen</h3>

<p class="info">
    <?php echo $this->project->name; ?> gebruikt de
    <a href="<?php echo $this->project->getBugsUrl(); ?>" rel="external" target="pulse_bugs"><?php echo $issueTracker . ' ' . $issueType; ?></a>
    voor de rapportage en verwerking van problemen.
    <br/>
    Voor een snelle verwerking van problemen verzoeken wij u de onderstaande suggesties te lezen.
</p>

<div class="indent">
    <h4>Maak een account<?php echo ($issueTracker ? (' op ' . $issueTracker) : ''); ?></h4>
    <p class="info">
        Je hebt een (gratis) account<?php echo ($issueTracker ? (' op ' . $issueTracker) : ''); ?> op problemen te rapporteren.
    </p>
    <h4>Meld elk probleem apart</h4>
    <p class="info">
        Elk probleem moet aan iemand toegewezen worden voor behandeling.
        Dit kan lastig zijn als verschillende problemen in &eacute;&eacute;n melding staan.
    </p>
    <h4>Voeg een link toe</h4>
    <p class="info">
        Als het probleem speelt op een specifieke pagina, kopieer dan het adres van de pagina uit de adresbalk van de browser.
    </p>
    <h4>Voeg een screenshot toe</h4>
    <p class="info">
        Met een screenshot kunnen wij een probleem meestal sneller oplossen.
    </p>
    <ul>
        <li>Druk op <span style="font-family: monospace;">[Alt]^[Print Screen]</span>.</li>
        <li>Open Paint of een ander tekenpakket of desnoods Word.</li>
        <li>Plak (paste) de inhoud van het clipboard en sla het bestand op.</li>
        <li>Voeg het bestand toe aan de melding.</li>
    </ul>
</div>

<h3>Meld het probleem</h3>

<p class="info">
    <a href="<?php echo $this->project->getBugsUrl(); ?>" rel="external" target="pulse_bugs">Hier</a> vindt u de
    <a href="<?php echo $this->project->getBugsUrl(); ?>" rel="external" target="pulse_bugs"><?php echo $issueTracker . ' ' . $issueType; ?></a>.
</p><?php
endif; ?>
