<?php
require_once 'Zend/Date.php';

/**
 * Test class for Gems_Event_EventCalculations.
 * Generated by PHPUnit on 2011-08-15 at 09:44:58.
 */
class MUtil_DateTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Mutil_Date
     */
    protected $object;

    /**
     * @var Zend_Translate_Adapter
     */
    protected $translate;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * Set up the translation adapter and set locale to 'en'
     */
    protected function setUp()
    {
        $this->object = new MUtil_Date();
        $english = array(
            '%s ago' => '%s ago',
            '%s to go' => '%s to go',
            'second' => array(0=>'second',
                              1=>'seconds'),
            'minute' => array(0=>'minute',
                              1=>'minutes'),
            'hour'   => array(0=>'hour',
                              1=>'hours'),
            'day'    => array(0=>'day',
                              1=>'days'),
            'week'   => array(0=>'week',
                              1=>'weeks'),
            'month'  => array(0=>'month',
                              1=>'months'),
            'year'   => array(0=>'year',
                              1=>'years'),
            'decade' => array(0=>'decade',
                              1=>'decades')
        );
        $dutch = array(
            '%s ago' => '%s geleden',
            '%s to go' => 'over %s',
            'second' => array(0=>'seconde',
                              1=>'seconden'),
            'minute' => array(0=>'minuut',
                              1=>'minuten'),
            'hour'   => array(0=>'uur',
                              1=>'uur'),
            'day'    => array(0=>'dag',
                              1=>'dagen'),
            'week'   => array(0=>'week',
                              1=>'weken'),
            'month'  => array(0=>'maand',
                              1=>'maanden'),
            'year'   => array(0=>'jaar',
                              1=>'jaren'),
            'decade' => array(0=>'decennium',
                              1=>'decennia')
        );
        $translate = new Zend_Translate(
            array(
                'adapter' => 'array',
                'content' => $english,
                'locale'  => 'en'
            )
        );
        $translate->addTranslation(array('content' => $dutch, 'locale' => 'nl'));

        $this->translate = $translate;
        $this->translate->setLocale('en');
    }

    public function testDiffReadableBeforeAndAfter() {
        $this->object = new MUtil_Date('2010-05-13 12:00:00');
        $testDate = new MUtil_Date('2010-05-13 12:00:10');
        $this->assertEquals('10 seconds ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 11:59:50');
        $this->assertEquals('10 seconds to go', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 12:00:00');
        $this->assertEquals('0 seconds to go', $this->object->diffReadable($testDate, $this->translate));
    }

    public function testDiffReadableBeforeAndAfterLocalised() {
        $this->translate->setLocale('nl');
        $this->object = new MUtil_Date('2010-05-13 12:00:00');
        $testDate = new MUtil_Date('2010-05-13 12:00:10');
        $this->assertEquals('10 seconden geleden', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 11:59:50');
        $this->assertEquals('over 10 seconden', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 12:00:00');
        $this->assertEquals('over 0 seconden', $this->object->diffReadable($testDate, $this->translate));
    }

    public function testDiffReadableSingularPlural() {
        $this->object = new MUtil_Date('2010-05-13 12:00:00');
        $testDate = new MUtil_Date('2010-05-13 12:01:00');
        $this->assertEquals('1 minute ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 12:02:00');
        $this->assertEquals('2 minutes ago', $this->object->diffReadable($testDate, $this->translate));
    }

    public function testDiffReadablePeriods() {
        $this->object = new MUtil_Date('2010-05-13 12:00:00');
        $testDate = new MUtil_Date('2010-05-13 12:00:01');
        $this->assertEquals('1 second ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 12:01:00');
        $this->assertEquals('1 minute ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-13 13:00:00');
        $this->assertEquals('1 hour ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-14 12:00:00');
        $this->assertEquals('1 day ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-05-20 12:00:00');
        $this->assertEquals('1 week ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2010-06-13 12:00:00');
        $this->assertEquals('1 month ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2011-05-13 12:00:01');
        $this->assertEquals('1 year ago', $this->object->diffReadable($testDate, $this->translate));
        $testDate = new MUtil_Date('2020-05-13 12:00:00');
        $this->assertEquals('1 decade ago', $this->object->diffReadable($testDate, $this->translate));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}