<?php echo $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta(); ?>

        <?php echo $this->headTitle(); ?>

    <?php echo $this->headLink(); ?>

    <?php echo $this->headStyle(); ?>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <?php
    // Check if jQuery library is needed
    if (MUtil_JQuery::usesJQuery($this)) {
        $jquery = $this->jQuery();
        $jquery->uiEnable(); // enable user interface
        $jquery->setUiVersion('1.8.9');
        $jquery->addStylesheet($this->baseUrl . '/scripts/jquery-ui-1.7.2.custom.css');

        if (MUtil_Https::on()) {
            $jquery->setCdnSsl(true);
        }

        echo $jquery;
    } ?>

    <?php
    // Check if bootstrap is needed
    if (MUtil_Bootstrap::usesBootstrap($this)) {
        $bootstrap = $this->bootstrap();

        if (MUtil_Https::on()) {
            $bootstrap->setCdnSsl(true);
        }

        echo $bootstrap;
    }
    ?>
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>