<?php
/**
 * @package    Gems
 * @subpackage Snippets
 * @copyright  Copyright (c) 2011 Erasmus MC
 * @license    New BSD License
 */

namespace Gems\Snippets\Respondent\Export;

use Gems\Legacy\CurrentUserRepository;
use Gems\User\User;
use Zalt\Base\RequestInfo;
use Zalt\Base\TranslatorInterface;
use Zalt\SnippetsLoader\SnippetOptions;

/**
 * Header for html/pdf export of a respondent
 *
 * @package    Gems
 * @subpackage Snippets
 * @copyright  Copyright (c) 2011 Erasmus MC
 * @license    New BSD License
 * @since      Class available since version 1.5.5
 */
class ReportHeaderSnippet extends \Zalt\Snippets\TranslatableSnippetAbstract
{
    protected User $currentUser;
    public function __construct(
        SnippetOptions $snippetOptions,
        RequestInfo $requestInfo,
        TranslatorInterface $translate,
        CurrentUserRepository $currentUserRepository,
    )
    {
        parent::__construct($snippetOptions, $requestInfo, $translate);

        $this->currentUser = $currentUserRepository->getCurrentUser();
    }

    public function getHtmlOutput(\Zend_View_Abstract $view = null)
    {
        $html = $this->getHtmlSequence();
        $html->h2($this->_('Respondent report'));

        $table = $html->table(array('class' => 'browser'));

        $table->th($this->_('Report information'), array('colspan' => 2));
        $tr = $table->tr();
        $tr->th($this->_('Generated by'));
        $tr->td($this->currentUser->getFullName());
        $tr = $table->tr();
        $tr->th($this->_('Generated on'));
        $tr->td(date('Y-m-d H:i:s'));
        $tr = $table->tr();
        $tr->th($this->_('Organization'));
        $tr->td($this->currentUser->getCurrentOrganization()->getName());

        $html->br();

        return $html;
    }
}